title: The Missing Umbrella
description: EGR314 Team 205 - Deepit Arora, Enoch Choi, Michael Gross
remote_theme: pages-themes/midnight@v0.2.0
show_downloads: "false"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
